apiVersion: v1
kind: Service
metadata:
  name: frontend-argo
  namespace: argocd
  labels:
    app: frontend-argo
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: frontend-argo-ports
  selector:
    app: frontend-argo
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: argocd
  labels:
    app: frontend-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-argo
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend-argo
        tier: frontend
    spec: # Pod spec
      containers:
        - name: frontend-container
          image: condorl/front-end-argo:v2.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "400m"    # 500milliCPUs (1/2 CPU)
            limits:
              memory: "512Mi"
              cpu: "500m"
